### PR TITLE
Eliminate some errors on bookworm

### PR DESCRIPTION
**Pull request by spoelstraethan**

### CODE REVIEW

**Comment by BLeeEZ** [comment]
Great work. Thank you for the updates.

**Comment by spoelstraethan** [comment]
I think one change that might be useful in a future update would be to not enable the GPIO control of an external text display unless the user opts in. My first attempt at using this package was on a Pi400 with a Hyperpixel LCD attached and the GPIO changes were causing the screen to cycle through weird color tinting.

One thing I didn't notice in the README was how to pair a new device, I think in one attempt I paired using the UI Bluetooth settings and then restarted rpi-kvm and it was able to utilize that pairing. I think I later realized that when the service starts it sets up the Bluetooth in discoverable mode all the time? It would be nice to be able to turn that on and off (via the CLI or web) as you may not want the extra RF noise or people attempting to pair unexpectedly.

I also discovered that while you can easily connect and disconnect and select an active device via the web there's not a way to unselect a device to direct inputs to the host OS, disconnecting the currently active device is effectively the same thing but not intuitive.

I'll probably open some additional issues with these feature requests and if I get a chance poke it some of the implementation myself.

**Comment by BLeeEZ** [comment]
These ideas all sound great. Every support is appreciated.

**Comment by BLeeEZ** [comment]
@spoelstraethan this PR is still marked as draft. I will submit this PR as soon as it is regularly open.

@argenkiwi I activated discussions for this project. Your post describes the reason why I started this project. I use a Dactyl Manuform with Colemak Mod-DH and wanted to have an easy way to access my devices.

**Comment by argenkiwi** [comment]
Thanks @BLeeEZ  for enabling discussions! I hope my post will attract some attention to this project. I admit I found it by coincidence while looking into an [issue](https://github.com/ruundii/bthidhub/issues/49) for a similar project that I failed to get to work. Your project is so much tidier and easier to install!

**Comment by spoelstraethan** [comment]
I haven't had a chance to test this recently, but if somebody can confirm it also works for them I think it is good to merge.

**Pull request merged**
